version: 0.0
os: linux
# jar 만 이동
files:
  - source: ./legowww.jar
    destination: /home/ubuntu/server
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
#  ApplicationStop: 기존 애플리케이션이 실행 중이라면 정지합니다.
#  DownloadBundle: S3에서 배포할 코드를 EC2 인스턴스로 다운로드합니다.
#  BeforeInstall: 필요한 경우, 설치 전에 실행할 스크립트를 실행합니다.
#  Install: 다운로드받은 코드를 원하는 위치에 설치합니다.
#  AfterInstall: 필요한 경우, 설치 후에 실행할 스크립트를 실행합니다.
#  CodeDeploy가 'Install' 단계에서 zip 파일을 압축 해제하고, appspec.yml 파일에 지정된 대로 해당 파일들을 EC2 인스턴스의 적절한 위치에 배치합니다. 즉, EC2 인스턴스에서는 압축이 해제된 파일들을 바로 사용할 수 있게 됩니다.
#  따라서, EC2 인스턴스에서는 zip 파일 형태가 아닌, 압축이 해제된 파일들을 다루게 됩니다. 이 과정은 CodeDeploy가 자동으로 처리해주므로, 사용자가 직접 압축을 해제할 필요는 없습니다.


  # 내 Ec2 로 옮겨진 gh_deploy.sh 를 사용하는 것
  ApplicationStart:
    - location: ./gh_deploy.sh
      timeout: 60
      runas: ubuntu
