name: MY-CI-CD

on:
  push:
    branches:
      - main
      - dev
env:
  S3_BUCKET_NAME: my-ec2-cp-bucket
  CODE_DEPLOY_APPLICATION_NAME: my-code-delpoy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: cdgrp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build
        shell: bash

        # CodeDeploy 에 사용할 script, 도커 파일, 도커 컴포즈와 appspec.yml 을 보내줘야 한다.
        # 1. jar 와 appspec.yml, script 를 저장할 디렉토리 temp 생성
        # 2. temp 에 jar 와 appspec.yml 복사
        # 3. temp 로 이동
        # 4. *.jar 의 이름을 legowww.jar 로 변경
        # 5. temp 에 있는 파일들을 압축하여 $GITHUB_SHA.zip 로 생성
      - name: Make zip file
        run: |
          mkdir -p temp 
          cp build/libs/*.jar temp
          cp appspec.yml temp
          cp scripts/gh_deploy.sh temp
          cd temp
          mv *.jar legowww.jar
          zip -r $GITHUB_SHA .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 6. temp 디렉토리의 $GITHUB_SHA.zip 파일을 S3에 전송
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 temp/$GITHUB_SHA.zip s3://$S3_BUCKET_NAME/$GITHUB_SHA.zip

      - name: Code Deploy
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,bundleType=zip,key=$GITHUB_SHA.zip

          
